version: '3'

services:
  db:
    restart: always
    image: postgres:12.1-alpine
    container_name: db-container
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=localuser
      - POSTGRES_PASSWORD=localpass
      - PGPASSWORD=localpass
      - POSTGRES_DB=localdb
      - DATABASE_HOST=localhost
    volumes:
      - ./persistence/init:/docker-entrypoint-initdb.d
        #      - ./persistence/data:/var/lib/postgresql/data/
