query customerConnection(
  $pageCondition: PageCondition
  $edgeOrder: EdgeOrder
  $filterWord: TextFilterCondition
) {
  customerConnection(
    pageCondition: $pageCondition
    edgeOrder: $edgeOrder
    filterWord: $filterWord
  ) {
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
    edges {
      node {
        id
        name
        age
      }
      cursor
    }
    totalCount
  }
}
