// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package backend

type Node interface {
	IsNode()
}

type CreateCsvCondition struct {
	UserID string `json:"userId"`
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type NewUser struct {
	Name string `json:"name"`
}

type NoopInput struct {
	ClientMutationID *string `json:"clientMutationId"`
}

type NoopPayload struct {
	ClientMutationID *string `json:"clientMutationId"`
}
