output   = "boiled"
pkgname  = "boiled"

[psql]
host   = "localhost"
port   = 25432
dbname = "study-graphql-local-db"
user   = "postgres"
pass   = "yuckyjuice"
sslmode= "disable"

blacklist = ["migration"]
